[package]
name = "enum-fun"
version = "0.1.5"
edition = "2024"
description = "Silly enum helpers."
repository = "https://github.com/tipsypastels/enum-fun"
license = "MIT"

[workspace]
members = [".", "./macros"]

[dependencies]
enum-fun-macros = { version = "0.1.5", path = "./macros" }
